<Project Sdk="Microsoft.NET.Sdk">
    
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;net5.0;net461;netstandard2.1;netstandard2.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>4.7.$(BuildNum)</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
    
  <ItemGroup>
    <None Remove="Dummy.txt" />
  </ItemGroup>
    
  <ItemGroup>
    <Content Include="Dummy.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>

    <Content Include="$(MSBuildThisFileDirectory)\..\README.md" Visible="False">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
    
  <ItemGroup>
    <PackageReference Include="JJ.AutoIncrementVersion" Version="4.7.6252" />
  </ItemGroup>

</Project>
