trigger:
- main

pool:
  name: Self-Hosted Agent Pool
  demands: msbuild

steps:
- task: janjoostvanzon.buildnum.build-num-task.BuildNum@1
  displayName: BuildNum

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet'
  inputs:
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'Restore with Dev-Feed'
  inputs:
    restoreSolution: 'JJ.AutoIncrementVersion.Test.sln'
    vstsFeed: '1de16010-421a-41a5-90f1-86e9513f2c5b/9ca4377d-62fa-4ac5-9da7-59fe48a43b8c'
  continueOnError: true

- task: MSBuild@1
  displayName: MSBuild
  inputs:
    solution: JJ.AutoIncrementVersion.Test.sln
    msbuildArchitecture: x64
    platform: 'Any CPU'
    configuration: Release
    msbuildArguments: '/p:BuildNum=$(BuildNum)'

- task: CopyFiles@2
  displayName: Stage
  inputs:
    Contents: |
     **/JJ.AutoIncrementVersion.*.nupkg
     **/JJ.AutoIncrementVersion.*.snupkg
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  enabled: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  enabled: false
