global using System.Diagnostics;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Xml.Linq;
global using System.Runtime.CompilerServices;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using JJ.Framework.Common.Legacy;
global using JJ.Framework.Common.Core;
global using JJ.Framework.Text.Core;
global using JJ.AutoIncrementVersion.Tests.docs;
global using static System.String;
global using static System.StringComparison;
global using static System.Guid;
global using static System.Text.RegularExpressions.Regex;
global using static System.Text.RegularExpressions.RegexOptions;
global using static System.IO.File;
global using static System.Reflection.Assembly;
global using static JJ.Framework.Exceptions.Core.Throw;
global using static JJ.Framework.Common.Legacy.EmbeddedResourceHelper;
global using static JJ.Framework.Testing.Core.AssertCore;
global using static JJ.AutoIncrementVersion.Tests.NoLog;
global using static JJ.AutoIncrementVersion.Tests.Logger;

