<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;net5.0;net461</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!--<WarningsAsErrors>Nullable</WarningsAsErrors>-->
    <WarningsAsErrors>True,Nullable</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JJ.Framework.Common.Legacy" Version="0.251.5752" />
    <PackageReference Include="JJ.Framework.PlatformCompatibility.Core.NuGet" Version="4.1.5756" />
    <PackageReference Include="JJ.Framework.Testing.Core" Version="4.1.5752" />
    <PackageReference Include="MSTest" Version="3.7.3" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\JJ.AutoIncrementVersion.Test\JJ.AutoIncrementVersion.Test.csproj" Link="TestResources\JJ.AutoIncrementVersion.Test.csproj" />
    <EmbeddedResource Include="..\Directory.Build.props" Link="TestResources\Directory.Build.props" />
    <EmbeddedResource Include="..\BuildNum.xml" Link="TestResources\BuildNum.xml" />
    <EmbeddedResource Include="..\NuGet.config" Link="TestResources\NuGet.config" />
    <EmbeddedResource Include="..\README.md" Link="TestResources\README.md" />
    <EmbeddedResource Include="..\JJ.AutoIncrementVersion.Test\Dummy.txt" Link="TestResources\Dummy.txt" />
  </ItemGroup>

</Project>
