global using System.Diagnostics;
global using System.Reflection;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Xml.Linq;
global using JJ.AutoIncrementVersion.TestSuite.Helpers;
global using static System.Console;
global using static System.StringComparison;
global using static System.IO.File;
global using static System.IO.Directory;
global using static JJ.Framework.Testing.Core.AssertCore;
